### PR TITLE
Sorting

### PR DESCRIPTION
**Pull request by ved0**
Added sorting to challenges.html
The user can now sort on lowest rating, highest rating and name (alphabetical order).

Added label that shows displayed challenges.

### CODE REVIEW

**Comment by Arash-SJPI22** [comment]
image

Looks good, but I think it would be good to change line 99 in challenges.html to change the "---" default value and set it to maybe highest or name ? Because after you have picked a value to sort from the "---" value is still there and dosen't do anything. Or add the "---" value to the sort.js so it dose something.

**Comment by rfabricioflores** [comment]
Smidig lösning! 
Jag hade gett taggen <select> mer styling för att få den att se lite snyggare ut, men jag tror inte att det är så viktigt, det fungerar bra i funktionalitet.  Bra jobbat!

**Comment by ved0** [comment]
> image
> 
> Looks good, but I think it would be good to change line 99 in challenges.html to change the "---" default value and set it to maybe highest or name ? Because after you have picked a value to sort from the "---" value is still there and dosen't do anything. Or add the "---" value to the sort.js so it dose something.

Noted. Thanks for the input :)

**Comment by ved0** [comment]
> Smidig lösning! Jag hade gett taggen mer styling för att få den att se lite snyggare ut, men jag tror inte att det är så viktigt, det fungerar bra i funktionalitet. Bra jobbat!

Noted. Thanks for the input :)

**Pull request merged**
